[package]
name = "sonr_extras"
version = "0.1.0"
authors = ["Jonas Hagstedt <hagstedt@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.4.12"
sonr = { git = "https://github.com/hagsteel/sonr" }
num_cpus = "1.10.0"
